/**
 * Tabela 24 TISS — Código CBO (Classificação Brasileira de Ocupações) aceito nas
 * guias. O valor gravado na guia é apenas o código de 6 caracteres; o rótulo
 * exibe código e ocupação para facilitar a escolha.
 */
export interface CboOption {
  code: string;
  name: string;
}

export const CBO_TABLE: CboOption[] = [
  { code: "131220", name: "Gerontólogo" },
  { code: "201115", name: "Geneticista" },
  { code: "203015", name: "Pesquisador em biologia de microorganismos e parasitas" },
  { code: "213150", name: "Físico médico" },
  { code: "221105", name: "Biólogo" },
  { code: "221205", name: "Biomédico" },
  { code: "223204", name: "Cirurgião dentista - auditor" },
  { code: "223208", name: "Cirurgião dentista - clínico geral" },
  { code: "223212", name: "Cirurgião dentista - endodontista" },
  { code: "223216", name: "Cirurgião dentista - epidemiologista" },
  { code: "223220", name: "Cirurgião dentista - estomatologista" },
  { code: "223224", name: "Cirurgião dentista - implantodontista" },
  { code: "223228", name: "Cirurgião dentista - odontogeriatra" },
  { code: "223232", name: "Cirurgião dentista - odontologista legal" },
  { code: "223236", name: "Cirurgião dentista - odontopediatra" },
  { code: "223240", name: "Cirurgião dentista - ortopedista e ortodontista" },
  { code: "223244", name: "Cirurgião dentista - patologista bucal" },
  { code: "223248", name: "Cirurgião dentista - periodontista" },
  { code: "223252", name: "Cirurgião dentista - protesiólogo bucomaxilofacial" },
  { code: "223256", name: "Cirurgião dentista - protesista" },
  { code: "223260", name: "Cirurgião dentista - radiologista" },
  { code: "223264", name: "Cirurgião dentista - reabilitador oral" },
  { code: "223268", name: "Cirurgião dentista - traumatologista bucomaxilofacial" },
  { code: "223272", name: "Cirurgião dentista de saúde coletiva" },
  { code: "223276", name: "Cirurgião dentista - odontologia do trabalho" },
  { code: "223280", name: "Cirurgião dentista - dentística" },
  { code: "223284", name: "Cirurgião dentista - disfunção temporomandibular e dor orofacial" },
  {
    code: "223288",
    name: "Cirurgião dentista - odontologia para pacientes com necessidades especiais",
  },
  { code: "223293", name: "Cirurgião-dentista da estratégia de saúde da família" },
  { code: "223405", name: "Farmacêutico" },
  { code: "223415", name: "Farmacêutico analista clínico" },
  { code: "223420", name: "Farmacêutico de alimentos" },
  { code: "223425", name: "Farmacêutico práticas integrativas e complementares" },
  { code: "223430", name: "Farmacêutico em saúde pública" },
  { code: "223435", name: "Farmacêutico industrial" },
  { code: "223440", name: "Farmacêutico toxicologista" },
  { code: "223445", name: "Farmacêutico hospitalar e clínico" },
  { code: "223505", name: "Enfermeiro" },
  { code: "223510", name: "Enfermeiro auditor" },
  { code: "223515", name: "Enfermeiro de bordo" },
  { code: "223520", name: "Enfermeiro de centro cirúrgico" },
  { code: "223525", name: "Enfermeiro de terapia intensiva" },
  { code: "223530", name: "Enfermeiro do trabalho" },
  { code: "223535", name: "Enfermeiro nefrologista" },
  { code: "223540", name: "Enfermeiro neonatologista" },
  { code: "223545", name: "Enfermeiro obstétrico" },
  { code: "223550", name: "Enfermeiro psiquiátrico" },
  { code: "223555", name: "Enfermeiro puericultor e pediátrico" },
  { code: "223560", name: "Enfermeiro sanitarista" },
  { code: "223565", name: "Enfermeiro da estratégia de saúde da família" },
  { code: "223570", name: "Perfusionista" },
  { code: "223605", name: "Fisioterapeuta geral" },
  { code: "223625", name: "Fisioterapeuta respiratória" },
  { code: "223630", name: "Fisioterapeuta neurofuncional" },
  { code: "223635", name: "Fisioterapeuta traumato-ortopédica funcional" },
  { code: "223640", name: "Fisioterapeuta osteopata" },
  { code: "223645", name: "Fisioterapeuta quiropraxista" },
  { code: "223650", name: "Fisioterapeuta acupunturista" },
  { code: "223655", name: "Fisioterapeuta esportivo" },
  { code: "223660", name: "Fisioterapeuta do trabalho" },
  { code: "223705", name: "Dietista" },
  { code: "223710", name: "Nutricionista" },
  { code: "223810", name: "Fonoaudiólogo" },
  { code: "223815", name: "Fonoaudiólogo educacional" },
  { code: "223820", name: "Fonoaudiólogo em audiologia" },
  { code: "223825", name: "Fonoaudiólogo em disfagia" },
  { code: "223830", name: "Fonoaudiólogo em linguagem" },
  { code: "223835", name: "Fonoaudiólogo em motricidade orofacial" },
  { code: "223840", name: "Fonoaudiólogo em saúde coletiva" },
  { code: "223845", name: "Fonoaudiólogo em voz" },
  { code: "223905", name: "Terapeuta ocupacional" },
  { code: "223910", name: "Ortoptista" },
  { code: "223915", name: "Psicomotricista" },
  { code: "224105", name: "Avaliador físico" },
  { code: "224110", name: "Ludomotricista" },
  { code: "224115", name: "Preparador de atleta" },
  { code: "224120", name: "Preparador físico" },
  { code: "224125", name: "Técnico de desporto individual e coletivo (exceto futebol)" },
  { code: "224130", name: "Técnico de laboratório e fiscalização desportiva" },
  { code: "224135", name: "Treinador profissional de futebol" },
  { code: "224140", name: "Profissional de educação física na saúde" },
  { code: "225103", name: "Médico infectologista" },
  { code: "225105", name: "Médico acupunturista" },
  { code: "225106", name: "Médico legista" },
  { code: "225109", name: "Médico Nefrologista" },
  { code: "225110", name: "Médico alergista e imunologista" },
  { code: "225112", name: "Médico neurologista" },
  { code: "225115", name: "Médico angiologista" },
  { code: "225118", name: "Médico nutrologista" },
  { code: "225120", name: "Médico cardiologista" },
  { code: "225121", name: "Médico oncologista clínico" },
  { code: "225122", name: "Médico cancerologista pediátrico" },
  { code: "225124", name: "Médico pediatra" },
  { code: "225125", name: "Médico clínico" },
  { code: "225127", name: "Médico pneumologista" },
  { code: "225130", name: "Médico de família e comunidade" },
  { code: "225133", name: "Médico psiquiatra" },
  { code: "225135", name: "Médico dermatologista" },
  { code: "225136", name: "Médico reumatologista" },
  { code: "225139", name: "Médico sanitarista" },
  { code: "225140", name: "Médico do trabalho" },
  { code: "225142", name: "Médico da estratégia de saúde da família" },
  { code: "225145", name: "Médico em medicina de tráfego" },
  { code: "225148", name: "Médico anatomopatologista" },
  { code: "225150", name: "Médico em medicina intensiva" },
  { code: "225151", name: "Médico anestesiologista" },
  { code: "225154", name: "Médico antroposófico" },
  { code: "225155", name: "Médico endocrinologista e metabologista" },
  { code: "225160", name: "Médico fisiatra" },
  { code: "225165", name: "Médico gastroenterologista" },
  { code: "225170", name: "Médico generalista" },
  { code: "225175", name: "Médico geneticista" },
  { code: "225180", name: "Médico geriatra" },
  { code: "225185", name: "Médico Hematologista" },
  { code: "225195", name: "Médico Homeopata" },
  { code: "225203", name: "Médico em cirurgia vascular" },
  { code: "225210", name: "Médico cirurgião cardiovascular" },
  { code: "225215", name: "Médico cirurgião de cabeça e pescoço" },
  { code: "225220", name: "Médico cirurgião do aparelho digestivo" },
  { code: "225225", name: "Médico cirurgião geral" },
  { code: "225230", name: "Médico cirurgião pediátrico" },
  { code: "225235", name: "Médico cirurgião plástico" },
  { code: "225240", name: "Médico cirurgião torácico" },
  { code: "225250", name: "Médico ginecologista e obstetra" },
  { code: "225255", name: "Médico Mastologista" },
  { code: "225260", name: "Médico neurocirurgião" },
  { code: "225265", name: "Médico oftalmologista" },
  { code: "225270", name: "Médico ortopedista e traumatologista" },
  { code: "225275", name: "Médico otorrinolaringologista" },
  { code: "225280", name: "Médico proctologista" },
  { code: "225285", name: "Médico urologista" },
  { code: "225290", name: "Médico cancerologista cirúrgico" },
  { code: "225295", name: "Médico cirurgião da mão" },
  { code: "225305", name: "Médico citopatologista" },
  { code: "225310", name: "Médico em endoscopia" },
  { code: "225315", name: "Médico em medicina nuclear" },
  { code: "225320", name: "Médico em radiologia e diagnóstico por imagem" },
  { code: "225325", name: "Médico patologista" },
  { code: "225330", name: "Médico radioterapeuta" },
  { code: "225335", name: "Médico patologista clínico / medicina laboratorial" },
  { code: "225340", name: "Médico hemoterapeuta" },
  { code: "225345", name: "Médico hiperbarista" },
  { code: "225350", name: "Médico neurofisiologista" },
  { code: "225355", name: "Médico radiologista intervencionista" },
  { code: "226105", name: "Quiropraxista" },
  { code: "226110", name: "Osteopata" },
  { code: "226305", name: "Musicoterapeuta" },
  { code: "226310", name: "Arteterapeuta" },
  { code: "226315", name: "Equoterapeuta" },
  { code: "226320", name: "Naturólogo" },
  { code: "239425", name: "Psicopedagogo" },
  { code: "239440", name: "Neuropsicopedagogo clinico" },
  { code: "239445", name: "Neuropsicopedagogo institucional" },
  { code: "251510", name: "Psicólogo clínico" },
  { code: "251545", name: "Neuropsicólogo" },
  { code: "251550", name: "Psicanalista" },
  { code: "251555", name: "Psicólogo acupunturista" },
  { code: "251605", name: "Assistente social" },
  { code: "322120", name: "Massoterapeuta" },
  { code: "322125", name: "Terapeuta holístico" },
  { code: "322135", name: "Doula" },
  { code: "322205", name: "Técnico de enfermagem" },
  { code: "322220", name: "Técnico de enfermagem psiquiátrica" },
  { code: "322225", name: "Instrumentador cirúrgico" },
  { code: "322230", name: "Auxiliar de enfermagem" },
  { code: "516210", name: "Cuidador de idosos" },
  { code: "999999", name: "CBO do prestador solicitante desconhecido ou não informado" },
];

/** Opções para selects: valor com 6 caracteres, rótulo com código e ocupação. */
export const CBO_OPTIONS = CBO_TABLE.map((item) => ({
  value: item.code,
  label: `${item.code} - ${item.name}`,
}));
