/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as PrescricaoRouteImport } from './routes/prescricao'
import { Route as OpmeRouteImport } from './routes/opme'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as EmitirRouteImport } from './routes/emitir'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DesignSystemIconesRouteImport } from './routes/design-system-icones'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CidRouteImport } from './routes/cid'
import { Route as IndexRouteImport } from './routes/index'

const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescricaoRoute = PrescricaoRouteImport.update({
  id: '/prescricao',
  path: '/prescricao',
  getParentRoute: () => rootRouteImport,
} as any)
const OpmeRoute = OpmeRouteImport.update({
  id: '/opme',
  path: '/opme',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const EmitirRoute = EmitirRouteImport.update({
  id: '/emitir',
  path: '/emitir',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemIconesRoute = DesignSystemIconesRouteImport.update({
  id: '/design-system-icones',
  path: '/design-system-icones',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CidRoute = CidRouteImport.update({
  id: '/cid',
  path: '/cid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cid': typeof CidRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
  '/documentos': typeof DocumentosRoute
  '/emitir': typeof EmitirRoute
  '/guias': typeof GuiasRoute
  '/opme': typeof OpmeRoute
  '/prescricao': typeof PrescricaoRoute
  '/procedimentos': typeof ProcedimentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cid': typeof CidRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
  '/documentos': typeof DocumentosRoute
  '/emitir': typeof EmitirRoute
  '/guias': typeof GuiasRoute
  '/opme': typeof OpmeRoute
  '/prescricao': typeof PrescricaoRoute
  '/procedimentos': typeof ProcedimentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cid': typeof CidRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
  '/documentos': typeof DocumentosRoute
  '/emitir': typeof EmitirRoute
  '/guias': typeof GuiasRoute
  '/opme': typeof OpmeRoute
  '/prescricao': typeof PrescricaoRoute
  '/procedimentos': typeof ProcedimentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cid'
    | '/dashboard'
    | '/design-system'
    | '/design-system-icones'
    | '/documentos'
    | '/emitir'
    | '/guias'
    | '/opme'
    | '/prescricao'
    | '/procedimentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cid'
    | '/dashboard'
    | '/design-system'
    | '/design-system-icones'
    | '/documentos'
    | '/emitir'
    | '/guias'
    | '/opme'
    | '/prescricao'
    | '/procedimentos'
  id:
    | '__root__'
    | '/'
    | '/cid'
    | '/dashboard'
    | '/design-system'
    | '/design-system-icones'
    | '/documentos'
    | '/emitir'
    | '/guias'
    | '/opme'
    | '/prescricao'
    | '/procedimentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CidRoute: typeof CidRoute
  DashboardRoute: typeof DashboardRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DesignSystemIconesRoute: typeof DesignSystemIconesRoute
  DocumentosRoute: typeof DocumentosRoute
  EmitirRoute: typeof EmitirRoute
  GuiasRoute: typeof GuiasRoute
  OpmeRoute: typeof OpmeRoute
  PrescricaoRoute: typeof PrescricaoRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescricao': {
      id: '/prescricao'
      path: '/prescricao'
      fullPath: '/prescricao'
      preLoaderRoute: typeof PrescricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opme': {
      id: '/opme'
      path: '/opme'
      fullPath: '/opme'
      preLoaderRoute: typeof OpmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emitir': {
      id: '/emitir'
      path: '/emitir'
      fullPath: '/emitir'
      preLoaderRoute: typeof EmitirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system-icones': {
      id: '/design-system-icones'
      path: '/design-system-icones'
      fullPath: '/design-system-icones'
      preLoaderRoute: typeof DesignSystemIconesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cid': {
      id: '/cid'
      path: '/cid'
      fullPath: '/cid'
      preLoaderRoute: typeof CidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CidRoute: CidRoute,
  DashboardRoute: DashboardRoute,
  DesignSystemRoute: DesignSystemRoute,
  DesignSystemIconesRoute: DesignSystemIconesRoute,
  DocumentosRoute: DocumentosRoute,
  EmitirRoute: EmitirRoute,
  GuiasRoute: GuiasRoute,
  OpmeRoute: OpmeRoute,
  PrescricaoRoute: PrescricaoRoute,
  ProcedimentosRoute: ProcedimentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
