/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as IndexRouteImport } from './routes/index'

const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guias': typeof GuiasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guias': typeof GuiasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guias': typeof GuiasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guias'
  id: '__root__' | '/' | '/guias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuiasRoute: typeof GuiasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuiasRoute: GuiasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
